### PR TITLE
Update to commit-a47ae1c27546bb27b7517184cbbd63e0b6b95138

### PR DESCRIPTION
**Pull request by wengxt**

### CODE REVIEW

**Comment by phoepsilonix** [comment]
It was necessary to write separately only for the cpython architecture.

It seems that the aarch64 files are also needed.

- mozc-deps.yaml
```yaml:mozc-deps.yaml
- type: file
  only-arches:
    - x86_64
  url: https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.11.9+20240415-x86_64-unknown-linux-gnu-install_only.tar.gz
  dest: bazel-deps
  sha256: 78b1c16a9fd032997ba92a60f46a64f795cd18ff335659dfdf6096df277b24d5
- type: file
  only-arches:
    - aarch64
  url: https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.11.9+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz
  dest: bazel-deps
  sha256: b3a7199ac2615d75fb906e5ba556432efcf24baf8651fc70370d9f052d4069ee
```

#12

**Comment by phoepsilonix** [comment]
I think if we make the above modifications, we should be able to update successfully.

Thank you for your hard work.

**Comment by phoepsilonix** [comment]
It might be a good idea to separate cpython into a separate file, just like we did with bazel(modules/bazel.yaml).

**Comment by phoepsilonix** [comment]
@wengxt
#13

**Comment by wengxt** [comment]
> It might be a good idea to separate cpython into a separate file, just like we did with bazel(modules/bazel.yaml).

Then we should try to automate this.

I actually have some progress with qemu binfmt and run an arch64 bazel  on x64 system

**Comment by phoepsilonix** [comment]
I understand.
fcitx/flatpak-fcitx5/pull/29

**Comment by phoepsilonix** [comment]
We have switched to updating using qemu(binfmt) and flatpak.
fcitx/flatpak-fcitx5/pull/29 is updated

**Pull request closed without merging**
